sudo: required
dist: precise

language: cpp

before-install:
  - sudo apt-get -qq update
  - sudo apt-get install -y pkg-config gawk libreadline-dev autoconf automake bison byacc flex help2man texinfo libc-ares-dev 

cache:
  directories:
  - $HOME/protobuf-build

install: 
  - ./install-protobuf
  - autoreconf --force -v
  # - ./update-autotools
  # - libtoolize -c
  # - automake --gnu --add-missing --copy

script:
  - ./configure --disable-doc --enable-vtysh --disable-ripd --disable-ripngd --disable-ospfd --disable-ospf6d --disable-babeld --disable-isisd --disable-opaque-lsa --disable-ospfclient --disable-ospf-te
  - sudo chmod -R 777 /var/run && sudo chmod -R 777 /usr/local/etc
  - make && sudo make install

notifications:
  email:
    - hsheth2@gmail.com
    - me@andrewsun.com
