sudo: required
dist: precise

language: cpp

before-install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gawk libreadline-dev autoconf automake bison byacc flex help2man texinfo libc-ares-dev 

install: 
  - ./update-autotools
  - autoreconf --force
  # - libtoolize -c
  # - automake --gnu --add-missing --copy

script:
  - ./configure --disable-doc --enable-vtysh --disable-ripd --disable-ripngd --disable-ospfd --disable-ospf6d --disable-babeld --disable-isisd --disable-opaque-lsa --disable-ospfclient --disable-ospf-te
  - make
  - sudo make install

notifications:
  email:
    - hsheth2@gmail.com
    - me@andrewsun.com
