#!/usr/bin/env bash

set -o xtrace

export PROTOBUF_VERSION=2.6.1
export PKG_CONFIG_PATH=$HOME/protobuf-$PROTOBUF_VERSION-bin/lib/pkgconfig

mkdir -p $HOME/protobuf-build
cd $HOME/protobuf-build

# install protobuf
if [ ! -d "protobuf-$PROTOBUF_VERSION" ]; then
	wget -nv https://github.com/google/protobuf/releases/download/v$PROTOBUF_VERSION/protobuf-$PROTOBUF_VERSION.tar.gz
	tar xf protobuf-$PROTOBUF_VERSION.tar.gz
	( cd protobuf-$PROTOBUF_VERSION && ./configure --prefix=$HOME/protobuf-$PROTOBUF_VERSION-bin && make -j2 )
fi
( cd protobuf-$PROTOBUF_VERSION && sudo make install )


# install protobuf-c
if [ ! -d "protobuf-c" ]; then
	git clone https://github.com/protobuf-c/protobuf-c
	( cd protobuf-c && ./autogen.sh && ./configure && make )
fi
( cd protobuf-c && sudo make install )

